config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  # READ - As a user, I can list tasks
  get 'tasks', to: 'tasks#index'
  # CREATE - As a user, I can add a new task
  # One route is there to display the Task form, and
  # the other is there to handle the POST request generated when submitting this form
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # UPDATE As a user, I can edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE As a user, I can remove a task
  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete_task'

  # As a user, I can view the details of a task
  get 'tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # /tasks/new
  def new
    #  display form with empty fields
    @task = Task.new
  end

  # /tasks/new
  def create
    # create new task with details entered by user
    @task = Task.new(task_params)   # (params[:task]) this will raise ActiveModel::ForbiddenAttributesError
    @task.save
    redirect_to tasks_path
  end

  # /tasks/:id/edit
  def edit
    # display form with filled in fields
    @task = Task.find(params[:id])
  end

  # /tasks/:id/edit
  def update
    #  find the Task to be edited, update values & redirect to details page (show)
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task.id) # show task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  # Strong Params
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <div class="container col-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div id="edit-task">
  <%= form_for(@task) do |f| %>
    <div class="form-group mb-3">
      <%= f.label :title%>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :details %>
      <%= f.text_field :details, class:"form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= f.check_box :completed %>
      <%= f.label :completed %>
    </div>
    <%= f.submit class:"btn btn-primary" %>
  <% end  %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1> My Task List</h1>
<ul>
<% @tasks.each do |task| %>
  <li><div id="task">
    <% icon = task.completed ?  '<i class="far fa-check-square"></i>' : '<i class="far fa-square"></i>' %>
    <%= icon.html_safe %> <%=  %>
    <%= link_to task.title, task_path(task.id) %>
  </div>
  <div id="task-delete">
    <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, delete_task_path(task), method: :delete,
    data: { confirm: 'Are you sure?' } %>
  </div></li>
<% end %>
</ul>
<hr>
<%= link_to '<i class="fas fa-plus"></i> Add a new task'.html_safe, tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<div >
  <p class="card p-4" ><%= @task.details %></p>
</div>
<%# <input type="checkbox" name="" id="completed"> %>
<%# <label for="completed">This task is not completed yet</label> %>
<!-- <%= form_for(@task) do |f| %>
  <%= f.check_box :completed %>
  <%= f.label :completed, 'This task is not completed yet!'%>
<% end %>> -->
<% if @task.completed %>
  <p><i class="fas fa-check-square"></i> This task is completed</p>
<% else %>
  <p><i class="far fa-square"></i> This task is not completed yet</p>
<% end %>
<br><br>
<%= link_to '<i class="fas fa-arrow-circle-left"></i> Back to list'.html_safe, root_path %>
<%= link_to '<i class="fas fa-edit"></i> Edit task'.html_safe, edit_task_path(@task) %>